apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-8
  labels:
    app: node1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: node1
  template:
    metadata:
      labels:
        app: node1

    spec:
      hostAliases:
      - ip: "172.20.160.28"
        hostnames:
         - "banqiodb"
      - ip: "172.20.160.31"
        hostnames:
         - "t24web"
      - ip: "172.20.113.35"
        hostnames:
         - "efsprint.akb.qa"
      containers:
      - name: node1
        image: ilayarajanabi/nginx:latest
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
      imagePullSecrets:
      - name: $KUBER_CONFIG

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: node1
spec:
  type: NodePort
  sessionAffinity: None
  selector:
     app: node1
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30100
